package com.lcp.common.enumeration;

public enum OperandType {
    STRING,     //CONTAIN,START_WITH,END_WITH,
    INTEGER,    //EQUAL, GREATER_EQUAL, LESS_EQUAL, BETWEEN
    DECIMAL,    //EQUAL, GREATER_EQUAL, LESS_EQUAL, BETWEEN
    DATE,       //EQUAL, GREATER_EQUAL, LESS_EQUAL, BETWEEN
    TIME,       //EQUAL, GREATER_EQUAL, LESS_EQUAL, BETWEEN
    DATETIME,   //EQUAL, GREATER_EQUAL, LESS_EQUAL, BETWEEN
    BOOLEAN,    //EQUAL
    ENUM
}
